version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile  # Make sure your unified Dockerfile is at root level or adjust path
    ports:
      - "80:80"
    networks:
      - reserva-network

networks:
  reserva-network:
    driver: bridge
