version: '3.8'

services:
  backend:
    build:
      context: ./backend
      target: production
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - reserva-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      target: production
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - reserva-network
    restart: unless-stopped

networks:
  reserva-network:
    driver: bridge